### ISSUE TITLE
Not all pages showing in menu builder

### ISSUE THREAD

**Issue by MarcPinnell** [kongondo/MenuBuilder#28]
Ran into an issue today where my pages were not showing in the menu builder interface. After some snooping, drop down page list is limited to 50 items. I found the fix on line 487 of the ProcessMenuBuilder.module. Changed "50" to "150" and all is well...

**Comment by kongondo** [comment]
@MarcPinnell . Actually, it is not an issue :-). 

I also [responded](https://processwire.com/talk/topic/4451-menu-builder/?do=findComment&comment=124077) to this in your post in the support forums. In a nutshell, Menu Builder already provides an inbuilt way for limiting (or for using any other selector you want) as long as you use the Asm Select or Page Auto Complete to add menu items. In your case, just add

> limit=150

 to the input **Pages selectable in menu**. Just above that field, by the way, there is a note about exactly this :-)...There is also a note on [line #486](https://github.com/kongondo/MenuBuilder/blob/master/ProcessMenuBuilder.module#L486) about the same. 

Anyway, for completeness, let me add that the normal practice is not to directly edit modules since such changes would get overwritten on each module upgrade....so all _would not be well_ :-)

Thanks for using Menu Builder.
